/**
simple multiplication table from 1 to 10
*/
#include<stdio.h>
int main()
{
	int i;
	for(i=1;i<=10;i++)
	{
		printf("1*%d=%d",i,1*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
	for(i=1;i<=10;i++)
	{
		printf("2*%d=%d",i,2*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("3*%d=%d",i,3*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("4*%d=%d",i,4*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("5*%d=%d",i,5*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("6*%d=%d",i,6*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("7*%d=%d",i,7*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("8*%d=%d",i,8*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("9*%d=%d",i,9*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
		for(i=1;i<=10;i++)
	{
		printf("10*%d=%d",i,10*i);
		printf("\n");
	}
	printf("*************************");
	printf("\n");
	return 0;
}
